"""Add Assessment model

Revision ID: d88967f612f1
Revises: daf05a7a974e
Create Date: 2024-07-07 00:19:30.403950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88967f612f1'
down_revision = 'daf05a7a974e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('technical_score', sa.Integer(), nullable=True),
    sa.Column('personality_traits', sa.String(length=255), nullable=True),
    sa.Column('communication_score', sa.Integer(), nullable=True),
    sa.Column('assessment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment')
    # ### end Alembic commands ###
